#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/buildroot-gcc342/bin/mipsel-linux-uclibc-gcc -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -DHAVE_CRYPTODEV -I../../include -DOPENSSL_SMALL_FOOTPRINT -DOPENSSL_NO_ERR -DOPENSSL_NO_HW -DTERMIO -O2 -fomit-frame-pointer -pipe  -Dlinux -D__linux__ -Dunix -DEMBED -I/data3/wu.xiaoyu/BR_SOHO_189_CHINA/MSG-WR201/source/lib/include -I/data3/wu.xiaoyu/BR_SOHO_189_CHINA/MSG-WR201/source/uClibc++/include -I/data3/wu.xiaoyu/BR_SOHO_189_CHINA/MSG-WR201/source  -fomit-frame-pointer -Wall"
  #define PLATFORM "linux-openwrt"
  #define DATE "Sat Jan  6 03:48:35 CST 2018"
#endif
